[project]
name = "weather-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "psycopg2[binary]>=2.9.10",
]
