name: weatherapp
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  web:
    build: ./backend
    command: >
      sh -c "uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data: